### ISSUE TITLE
How is this repository updated?

### ISSUE THREAD

**Issue by eyeinsky** [sharkcz/collectl#1]
Hi and thanks for hosting this on github! Do you mind saying and perhaps even adding a document to the repository on how this is updated for every new version? I.e, is collectl itself another github repository somewhere else, or if not, is the new version just extracted over the most recent commit and then have git figure out what has changed? Also, how are the commit messages created, e.g, are they taken from a changelog?

Thanks!

**Comment by loberman** [comment]
Hello.  As fixes are done commits are created and this updates the latest collectl github.
A git pull gets the latest fixes. The work done is maintenance only, bug fixes and ensuring the versions work on RHEL and Fedora. IF anybody has issues on non RHEL they are expected to email me at loberman@redhat.com so I can address that.

Her are the last 3 commits as an example

commit f63951f72215db9d7957f91ab9f9c32ccbe681d3 (HEAD -> master, origin/master, origin/HEAD)
Author: Laurence Oberman <loberman@redhat.com>
Date:   Tue Jan 2 11:18:37 2024 -0500

    Version 4.3.9 with md added for disks

commit 471bc215ec366e960a1989c4da188b2493e24148
Author: Laurence Oberman <loberman@redhat.com>
Date:   Tue Aug 1 16:23:27 2023 -0400

    Added md devices to disk parse

**Comment by eyeinsky** [comment]
Thank you for the reply! Does this mean there an internal git repository somewhere which is pulled, and then pushed here to github?

**Comment by loberman** [comment]
Hello 
Dan hosted this for Fedora updates and when I moved from using Sourceforge to git hub, I have a local repository on my Fedora workstation I develop on,and then I push my commits to  https://github.com/sharkcz/collectl.git.

I will update a README about this process do it is documented.

**Comment by eyeinsky** [comment]
Got it!

I would say that even though the About field ([here in right column](https://github.com/sharkcz/collectl/)) for this repository says "git mirror of collectl releases" then actually this repository is the main (public) source for the `collectl` tool as all new changes are distributed from here?
