### ISSUE TITLE
Tagging new releases?

### ISSUE THREAD

**Issue by benfulton** [sharkcz/collectl#2]
The last commit (as of 6/5/24) shows version 4.3.9, but there doesn't seem to be a tag matching that version. Is this commit officially that version?

**Comment by loberman** [comment]
Yes it its but that tag was not updated. I will correct that. We have had issues since we stopped updating on Sourceforge. We took the snap and switched to git and continued maintaining this. The git repo was already in use for collectl for Fedora.

**Comment by loberman** [comment]
OK, new release created with the correct tag. 
Thank you for bringing that to my attention.

**Comment by benfulton** [comment]
Thanks!
